const dateDaysAgo = (days: number) => {
  const date = new Date();
  date.setDate(date.getDate() - days);
  return date.toISOString();
};

export type DemoLead = {
  id: string;
  name: string;
  email: string;
  phone: string;
  source: string;
  location: string;
  budget: string;
  status: string;
  stage: string;
  timeline: string;
  lastContact: string;
  notes: string;
  score: number;
  createdAt: string;
};

export type DemoDocument = {
  id: string;
  title: string;
  property: string;
  size: string;
  uploadedAt: string;
  status: "processing" | "ready";
};

export type DemoDeal = {
  id: string;
  property: string;
  buyer: string;
  seller: string;
  closedOn: string;
  price: string;
  commission: string;
  neighborhood: string;
};

export type DemoConversationMessage = {
  id: string;
  sender: "client" | "agent" | "assistant";
  body: string;
  timestamp: string;
};

export type DemoConversation = {
  id: string;
  clientName: string;
  avatarHue: number;
  property: string;
  summary: string;
  unread: boolean;
  messages: DemoConversationMessage[];
};

export type DemoProperty = {
  id: string;
  title: string;
  image: string;
  gallery: string[];
  address: string;
  price: string;
  bedrooms: number;
  bathrooms: number;
  area: string;
  description: string;
  highlights: string[];
  url: string;
};

export type DemoNotification = {
  id: string;
  title: string;
  detail: string;
  timestamp: string;
};

const leadLibraryBase: Array<Omit<DemoLead, "id" | "createdAt"> & { createdAtDaysAgo: number }> = [
  {
    name: "Sarah Williams",
    email: "sarah.williams@luxeoffers.com",
    phone: "+1 (512) 540-2289",
    source: "Zillow",
    location: "Austin, TX",
    budget: "$620,000",
    status: "Active Lead",
    stage: "Tour Scheduling",
    timeline: "1-3 months",
    lastContact: "2 days ago",
    notes: "Modern 3-bed homes near award winning schools. Requests evening showings.",
    score: 91,
    createdAtDaysAgo: 4,
  },
  {
    name: "David Chen",
    email: "david.chen@foundersuite.com",
    phone: "+1 (415) 287-9032",
    source: "Referral",
    location: "San Francisco, CA",
    budget: "$1,850,000",
    status: "Hot Lead",
    stage: "Financing",
    timeline: "Immediate",
    lastContact: "Today",
    notes: "Series B founder relocating closer to HQ. Prefers new construction with rooftop deck.",
    score: 96,
    createdAtDaysAgo: 1,
  },
  {
    name: "Olivia Martinez",
    email: "olivia.martinez@modhomes.co",
    phone: "+1 (305) 667-9031",
    source: "Instagram Ads",
    location: "Miami, FL",
    budget: "$950,000",
    status: "Active Lead",
    stage: "Needs Analysis",
    timeline: "3-6 months",
    lastContact: "3 days ago",
    notes: "Looking for waterfront property with space for art studio. Wants smart home features.",
    score: 82,
    createdAtDaysAgo: 6,
  },
  {
    name: "Marcus Johnson",
    email: "marcus.johnson@launchpad.io",
    phone: "+1 (206) 421-1085",
    source: "Open House",
    location: "Seattle, WA",
    budget: "$1,120,000",
    status: "Nurture",
    stage: "Research",
    timeline: "6+ months",
    lastContact: "5 days ago",
    notes: "Interested in modern townhomes near light rail. Needs separate workspace for podcast studio.",
    score: 71,
    createdAtDaysAgo: 10,
  },
  {
    name: "Priya Patel",
    email: "priya.patel@atlasfinancial.com",
    phone: "+1 (917) 825-4309",
    source: "Google PPC",
    location: "New York, NY",
    budget: "$2,450,000",
    status: "Hot Lead",
    stage: "Offer Preparation",
    timeline: "1 month",
    lastContact: "Yesterday",
    notes: "Needs dual office setup and concierge level amenities. Prefers Tribeca loft conversions.",
    score: 94,
    createdAtDaysAgo: 3,
  },
  {
    name: "Ethan Brooks",
    email: "ethan.brooks@venturelaunch.com",
    phone: "+1 (480) 900-5544",
    source: "Zillow",
    location: "Scottsdale, AZ",
    budget: "$1,180,000",
    status: "Active Lead",
    stage: "Tour Scheduling",
    timeline: "0-30 days",
    lastContact: "Today",
    notes: "Searching for golf course community with casita for in-laws. Ready to make offers.",
    score: 89,
    createdAtDaysAgo: 2,
  },
  {
    name: "Hannah Kim",
    email: "hannah.kim@medianexus.com",
    phone: "+1 (213) 608-7721",
    source: "Past Client",
    location: "Los Angeles, CA",
    budget: "$3,200,000",
    status: "Repeat Client",
    stage: "Listing Presentation",
    timeline: "2 months",
    lastContact: "4 days ago",
    notes: "Selling current Hollywood Hills property to upgrade view estate. Wants staging proposal.",
    score: 87,
    createdAtDaysAgo: 8,
  },
  {
    name: "Jackson Rivera",
    email: "jackson.rivera@aerialcreative.io",
    phone: "+1 (786) 320-5531",
    source: "YouTube",
    location: "Miami, FL",
    budget: "$780,000",
    status: "Active Lead",
    stage: "Discovery Call",
    timeline: "3 months",
    lastContact: "1 week ago",
    notes: "Needs content-ready rooftop spaces for lifestyle brand shoots. Prefers Brickell high-rises.",
    score: 68,
    createdAtDaysAgo: 12,
  },
  {
    name: "Emily Thompson",
    email: "emily.thompson@wellnesshq.com",
    phone: "+1 (404) 315-6672",
    source: "Referral",
    location: "Atlanta, GA",
    budget: "$910,000",
    status: "Hot Lead",
    stage: "Tour Scheduling",
    timeline: "45 days",
    lastContact: "1 day ago",
    notes: "Relocating for wellness center expansion. Needs separate guest suite and yoga deck.",
    score: 90,
    createdAtDaysAgo: 5,
  },
  {
    name: "Noah Garcia",
    email: "noah.garcia@stadiumlabs.com",
    phone: "+1 (214) 744-2199",
    source: "Event",
    location: "Dallas, TX",
    budget: "$890,000",
    status: "Active Lead",
    stage: "Financing",
    timeline: "2 months",
    lastContact: "3 days ago",
    notes: "Seeking Highland Park new build with smart security package. Loan pre-approval in progress.",
    score: 83,
    createdAtDaysAgo: 9,
  },
  {
    name: "Ava Robinson",
    email: "ava.robinson@designmodo.studio",
    phone: "+1 (704) 775-9341",
    source: "Instagram Ads",
    location: "Charlotte, NC",
    budget: "$740,000",
    status: "Active Lead",
    stage: "Discovery Call",
    timeline: "4 months",
    lastContact: "6 days ago",
    notes: "Interior designer wanting historic bungalow with modern addition. Requests local builder roster.",
    score: 76,
    createdAtDaysAgo: 14,
  },
  {
    name: "Liam Bennett",
    email: "liam.bennett@precision.ai",
    phone: "+1 (617) 339-2215",
    source: "LinkedIn",
    location: "Boston, MA",
    budget: "$1,540,000",
    status: "Hot Lead",
    stage: "Offer Negotiation",
    timeline: "Immediate",
    lastContact: "Today",
    notes: "VP of engineering relocating from Palo Alto. Wants turnkey brownstone with EV infrastructure.",
    score: 95,
    createdAtDaysAgo: 1,
  },
  {
    name: "Isabella Collins",
    email: "isabella.collins@studioeight.co",
    phone: "+1 (970) 555-2134",
    source: "Referral",
    location: "Denver, CO",
    budget: "$1,020,000",
    status: "Nurture",
    stage: "Research",
    timeline: "5 months",
    lastContact: "2 weeks ago",
    notes: "Wants Wash Park craftsman with finished basement zen studio. Prefers energy-efficient updates.",
    score: 67,
    createdAtDaysAgo: 16,
  },
  {
    name: "Michael Nguyen",
    email: "michael.nguyen@quantumglobal.xyz",
    phone: "+1 (408) 643-7712",
    source: "Past Client",
    location: "San Jose, CA",
    budget: "$2,780,000",
    status: "Repeat Client",
    stage: "Listing Prep",
    timeline: "60 days",
    lastContact: "Yesterday",
    notes: "Selling investment condo and upgrading to smart estate with solar roof and infinity pool.",
    score: 88,
    createdAtDaysAgo: 7,
  },
  {
    name: "Zoe Harris",
    email: "zoe.harris@atlanticmedia.co",
    phone: "+1 (718) 424-9932",
    source: "Open House",
    location: "Brooklyn, NY",
    budget: "$1,450,000",
    status: "Active Lead",
    stage: "Tour Scheduling",
    timeline: "90 days",
    lastContact: "4 days ago",
    notes: "Prefers loft with exposed brick and freight elevator access for weekly shoots.",
    score: 78,
    createdAtDaysAgo: 11,
  },
  {
    name: "Henry Clark",
    email: "henry.clark@vertexcapital.com",
    phone: "+1 (832) 543-2176",
    source: "Referral",
    location: "Houston, TX",
    budget: "$1,350,000",
    status: "Hot Lead",
    stage: "Offer Review",
    timeline: "Immediate",
    lastContact: "Today",
    notes: "Oil and gas executive seeking Memorial estate with pool house. Legal reviewing contracts.",
    score: 92,
    createdAtDaysAgo: 2,
  },
  {
    name: "Layla Anderson",
    email: "layla.anderson@summitwellness.com",
    phone: "+1 (503) 221-9911",
    source: "Google PPC",
    location: "Portland, OR",
    budget: "$860,000",
    status: "Active Lead",
    stage: "Discovery Call",
    timeline: "3-4 months",
    lastContact: "5 days ago",
    notes: "Needs walkable community near trails. Interested in net zero certified builders.",
    score: 74,
    createdAtDaysAgo: 13,
  },
  {
    name: "Mateo Sanchez",
    email: "mateo.sanchez@creativeworks.mx",
    phone: "+1 (210) 584-2045",
    source: "Event",
    location: "San Antonio, TX",
    budget: "$680,000",
    status: "Active Lead",
    stage: "Tour Scheduling",
    timeline: "45 days",
    lastContact: "3 days ago",
    notes: "Looking for hill country views with detached studio. Prefers Spanish Revival architecture.",
    score: 81,
    createdAtDaysAgo: 9,
  },
  {
    name: "Harper Lee",
    email: "harper.lee@foundryventures.io",
    phone: "+1 (312) 618-7092",
    source: "LinkedIn",
    location: "Chicago, IL",
    budget: "$1,080,000",
    status: "Hot Lead",
    stage: "Financing",
    timeline: "60 days",
    lastContact: "Today",
    notes: "Needs skyline views and private terrace. Bank underwriting final mortgage approval.",
    score: 90,
    createdAtDaysAgo: 3,
  },
  {
    name: "Sofia Torres",
    email: "sofia.torres@ateliergroup.co",
    phone: "+1 (305) 331-8840",
    source: "Instagram Ads",
    location: "Miami Beach, FL",
    budget: "$1,520,000",
    status: "Active Lead",
    stage: "Discovery Call",
    timeline: "2-3 months",
    lastContact: "Yesterday",
    notes: "Creative director wants Art Deco penthouse with sunrise views. Prefers boutique buildings.",
    score: 86,
    createdAtDaysAgo: 6,
  },
  {
    name: "Mason Hughes",
    email: "mason.hughes@frontierlogistics.com",
    phone: "+1 (702) 443-8801",
    source: "Zillow",
    location: "Las Vegas, NV",
    budget: "$1,040,000",
    status: "Active Lead",
    stage: "Tour Scheduling",
    timeline: "30 days",
    lastContact: "2 days ago",
    notes: "Wants guard gated community with six car garage. Prefers modern desert architecture.",
    score: 84,
    createdAtDaysAgo: 5,
  },
  {
    name: "Grace Walker",
    email: "grace.walker@harborlight.co",
    phone: "+1 (904) 510-7330",
    source: "Referral",
    location: "Jacksonville, FL",
    budget: "$720,000",
    status: "Active Lead",
    stage: "Needs Analysis",
    timeline: "90 days",
    lastContact: "1 week ago",
    notes: "Relocating from Raleigh. Wants coastal community with top rated academies.",
    score: 77,
    createdAtDaysAgo: 15,
  },
  {
    name: "Julian Perez",
    email: "julian.perez@urbanbeat.io",
    phone: "+1 (917) 909-1822",
    source: "TikTok",
    location: "Brooklyn, NY",
    budget: "$980,000",
    status: "Active Lead",
    stage: "Discovery Call",
    timeline: "4 months",
    lastContact: "5 days ago",
    notes: "Music producer needs soundproof flex room and rooftop for events.",
    score: 73,
    createdAtDaysAgo: 11,
  },
  {
    name: "Chloe Adams",
    email: "chloe.adams@northshore.vc",
    phone: "+1 (312) 220-1187",
    source: "LinkedIn",
    location: "Chicago, IL",
    budget: "$1,260,000",
    status: "Hot Lead",
    stage: "Financing",
    timeline: "45 days",
    lastContact: "Today",
    notes: "Private equity partner seeking River North condo with concierge and valet.",
    score: 92,
    createdAtDaysAgo: 2,
  },
  {
    name: "Nathan Scott",
    email: "nathan.scott@revivefitness.io",
    phone: "+1 (615) 744-2203",
    source: "Google PPC",
    location: "Nashville, TN",
    budget: "$830,000",
    status: "Active Lead",
    stage: "Tour Scheduling",
    timeline: "60 days",
    lastContact: "Yesterday",
    notes: "Fitness founder wants home gym and sound studio. Prefers modern farmhouses.",
    score: 85,
    createdAtDaysAgo: 7,
  },
  {
    name: "Maya Foster",
    email: "maya.foster@coastcollective.com",
    phone: "+1 (858) 341-2124",
    source: "Referral",
    location: "San Diego, CA",
    budget: "$1,280,000",
    status: "Active Lead",
    stage: "Discovery Call",
    timeline: "3 months",
    lastContact: "3 days ago",
    notes: "Surf brand founder needs beach access and guest casita. Interested in Del Mar moderns.",
    score: 82,
    createdAtDaysAgo: 9,
  },
  {
    name: "Lucas Ramirez",
    email: "lucas.ramirez@atlascollective.mx",
    phone: "+1 (713) 220-5521",
    source: "Event",
    location: "Houston, TX",
    budget: "$1,150,000",
    status: "Hot Lead",
    stage: "Offer Drafting",
    timeline: "30 days",
    lastContact: "Today",
    notes: "Oil services executive relocating from Monterrey. Needs bilingual school nearby.",
    score: 93,
    createdAtDaysAgo: 1,
  },
  {
    name: "Gianna Russo",
    email: "gianna.russo@lunarstudio.it",
    phone: "+1 (917) 451-6620",
    source: "Instagram Ads",
    location: "New York, NY",
    budget: "$2,300,000",
    status: "Active Lead",
    stage: "Tour Scheduling",
    timeline: "60 days",
    lastContact: "2 days ago",
    notes: "Fashion creative director wants pre-war loft with marble chef kitchen. Needs art storage.",
    score: 88,
    createdAtDaysAgo: 4,
  },
  {
    name: "Elijah Brooks",
    email: "elijah.brooks@midwestforge.com",
    phone: "+1 (816) 301-7789",
    source: "Zillow",
    location: "Kansas City, MO",
    budget: "$640,000",
    status: "Active Lead",
    stage: "Needs Analysis",
    timeline: "6 months",
    lastContact: "8 days ago",
    notes: "Wants family estate with acreage and workshop. Interested in EV chargers.",
    score: 69,
    createdAtDaysAgo: 17,
  },
  {
    name: "Aria Morgan",
    email: "aria.morgan@studioatlas.co",
    phone: "+1 (404) 834-9921",
    source: "Referral",
    location: "Atlanta, GA",
    budget: "$980,000",
    status: "Active Lead",
    stage: "Tour Scheduling",
    timeline: "45 days",
    lastContact: "4 days ago",
    notes: "Film producer wants Midtown penthouse with skyline terrace and media room.",
    score: 84,
    createdAtDaysAgo: 6,
  },
  {
    name: "Carter Long",
    email: "carter.long@harborfin.co",
    phone: "+1 (206) 338-9021",
    source: "LinkedIn",
    location: "Seattle, WA",
    budget: "$1,180,000",
    status: "Hot Lead",
    stage: "Offer Negotiation",
    timeline: "Immediate",
    lastContact: "Today",
    notes: "Fintech CFO relocating downtown. Needs smart security and EV ready parking.",
    score: 94,
    createdAtDaysAgo: 2,
  },
  {
    name: "Penelope Ward",
    email: "penelope.ward@violetstudio.co",
    phone: "+1 (801) 771-2004",
    source: "Pinterest",
    location: "Salt Lake City, UT",
    budget: "$780,000",
    status: "Active Lead",
    stage: "Discovery Call",
    timeline: "90 days",
    lastContact: "7 days ago",
    notes: "Lifestyle influencer wants mid-century modern with mountain views and sauna.",
    score: 75,
    createdAtDaysAgo: 12,
  },
  {
    name: "Dominic Price",
    email: "dominic.price@skywardair.io",
    phone: "+1 (480) 662-1930",
    source: "YouTube",
    location: "Phoenix, AZ",
    budget: "$940,000",
    status: "Active Lead",
    stage: "Tour Scheduling",
    timeline: "30 days",
    lastContact: "3 days ago",
    notes: "Aviation entrepreneur needs hangar capable property with guest quarters.",
    score: 81,
    createdAtDaysAgo: 8,
  },
  {
    name: "Victoria Blake",
    email: "victoria.blake@harperlane.com",
    phone: "+1 (617) 900-2145",
    source: "Referral",
    location: "Boston, MA",
    budget: "$1,780,000",
    status: "Active Lead",
    stage: "Offer Preparation",
    timeline: "45 days",
    lastContact: "Yesterday",
    notes: "Luxury travel blogger wants Beacon Hill townhouse with private courtyard.",
    score: 89,
    createdAtDaysAgo: 5,
  },
  {
    name: "Sebastian Cruz",
    email: "sebastian.cruz@latinstudio.mx",
    phone: "+1 (917) 422-1180",
    source: "Open House",
    location: "Queens, NY",
    budget: "$920,000",
    status: "Nurture",
    stage: "Research",
    timeline: "6 months",
    lastContact: "2 weeks ago",
    notes: "Wants two family with rental income. Prefers Jackson Heights historic district.",
    score: 66,
    createdAtDaysAgo: 18,
  },
  {
    name: "Nora Simmons",
    email: "nora.simmons@atlaslawpartners.com",
    phone: "+1 (704) 214-6622",
    source: "LinkedIn",
    location: "Charlotte, NC",
    budget: "$860,000",
    status: "Active Lead",
    stage: "Financing",
    timeline: "60 days",
    lastContact: "2 days ago",
    notes: "Corporate attorney needs home office with library wall and proximity to Uptown courts.",
    score: 83,
    createdAtDaysAgo: 6,
  },
  {
    name: "Adrian Flores",
    email: "adrian.flores@peakgaming.gg",
    phone: "+1 (702) 311-9020",
    source: "Twitch",
    location: "Las Vegas, NV",
    budget: "$1,050,000",
    status: "Active Lead",
    stage: "Tour Scheduling",
    timeline: "45 days",
    lastContact: "3 days ago",
    notes: "Esports founder wants streaming bunker and blackout drapes. Prefers Henderson hills.",
    score: 80,
    createdAtDaysAgo: 9,
  },
  {
    name: "Riley Matthews",
    email: "riley.matthews@harborcollective.com",
    phone: "+1 (206) 709-5522",
    source: "Past Client",
    location: "Seattle, WA",
    budget: "$1,320,000",
    status: "Repeat Client",
    stage: "Listing Prep",
    timeline: "60 days",
    lastContact: "Yesterday",
    notes: "Upgrading from condo to lakefront estate. Needs smart dock and sauna.",
    score: 88,
    createdAtDaysAgo: 4,
  },
  {
    name: "Stella Cooper",
    email: "stella.cooper@midnightatelier.com",
    phone: "+1 (312) 609-4420",
    source: "Instagram Ads",
    location: "Chicago, IL",
    budget: "$1,160,000",
    status: "Active Lead",
    stage: "Discovery Call",
    timeline: "90 days",
    lastContact: "5 days ago",
    notes: "Boutique agency owner needs glass walled studio and private client lounge.",
    score: 79,
    createdAtDaysAgo: 10,
  },
  {
    name: "Owen Mitchell",
    email: "owen.mitchell@lakesidecapital.com",
    phone: "+1 (615) 771-2190",
    source: "Referral",
    location: "Nashville, TN",
    budget: "$1,120,000",
    status: "Active Lead",
    stage: "Offer Negotiation",
    timeline: "Immediate",
    lastContact: "Today",
    notes: "Private equity partner wants gated Brentwood estate with recording lounge.",
    score: 93,
    createdAtDaysAgo: 2,
  },
];

export const demoLeadLibrary: DemoLead[] = leadLibraryBase.map((lead, index) => ({
  ...lead,
  id: `demo-lead-${index + 1}`,
  createdAt: dateDaysAgo(lead.createdAtDaysAgo),
}));

export const demoDocumentLibrary: DemoDocument[] = [
  {
    id: "demo-doc-1",
    title: "Purchase Agreement - 123 Palm Grove.pdf",
    property: "123 Palm Grove, Miami Beach FL",
    size: "1.8 MB",
    uploadedAt: dateDaysAgo(2),
    status: "ready",
  },
  {
    id: "demo-doc-2",
    title: "Inspection Report - 77 Harbor View.pdf",
    property: "77 Harbor View, Newport Beach CA",
    size: "2.1 MB",
    uploadedAt: dateDaysAgo(3),
    status: "ready",
  },
  {
    id: "demo-doc-3",
    title: "Financing Addendum - 88 Beacon St.pdf",
    property: "88 Beacon St, Boston MA",
    size: "1.4 MB",
    uploadedAt: dateDaysAgo(2),
    status: "processing",
  },
  {
    id: "demo-doc-4",
    title: "Disclosures - 52 Modern Ridge.pdf",
    property: "52 Modern Ridge, Austin TX",
    size: "3.2 MB",
    uploadedAt: dateDaysAgo(6),
    status: "ready",
  },
  {
    id: "demo-doc-5",
    title: "Closing Statement - 401 Skyline Ave.pdf",
    property: "401 Skyline Ave, Denver CO",
    size: "980 KB",
    uploadedAt: dateDaysAgo(9),
    status: "ready",
  },
  {
    id: "demo-doc-6",
    title: "Counter Offer - 19 Seaside Lane.pdf",
    property: "19 Seaside Lane, Laguna Beach CA",
    size: "1.7 MB",
    uploadedAt: dateDaysAgo(1),
    status: "processing",
  },
  {
    id: "demo-doc-7",
    title: "Title Commitment - 702 Elm Estate.pdf",
    property: "702 Elm Estate, Nashville TN",
    size: "2.9 MB",
    uploadedAt: dateDaysAgo(5),
    status: "ready",
  },
  {
    id: "demo-doc-8",
    title: "HOA Bylaws - 550 Lakeshore Dr.pdf",
    property: "550 Lakeshore Dr, Chicago IL",
    size: "4.6 MB",
    uploadedAt: dateDaysAgo(8),
    status: "ready",
  },
  {
    id: "demo-doc-9",
    title: "Buyer Presentation - Rivera Family.pdf",
    property: "Presentation Deck",
    size: "6.4 MB",
    uploadedAt: dateDaysAgo(4),
    status: "ready",
  },
  {
    id: "demo-doc-10",
    title: "Staging Proposal - 18 Willow Court.pdf",
    property: "18 Willow Court, Austin TX",
    size: "850 KB",
    uploadedAt: dateDaysAgo(7),
    status: "ready",
  },
];

export const demoDealsHistory: DemoDeal[] = [
  {
    id: "demo-deal-1",
    property: "721 Willow Drive, Austin TX",
    buyer: "John Carter",
    seller: "Zilker Estates LLC",
    closedOn: dateDaysAgo(27),
    price: "$1,180,000",
    commission: "$35,400",
    neighborhood: "Zilker",
  },
  {
    id: "demo-deal-2",
    property: "88 Beacon St, Boston MA",
    buyer: "Priya Patel",
    seller: "Beacon Square Holdings",
    closedOn: dateDaysAgo(18),
    price: "$2,320,000",
    commission: "$69,600",
    neighborhood: "Back Bay",
  },
  {
    id: "demo-deal-3",
    property: "19 Seaside Lane, Laguna Beach CA",
    buyer: "Olivia Martinez",
    seller: "Sunset Shores LLC",
    closedOn: dateDaysAgo(32),
    price: "$3,180,000",
    commission: "$95,400",
    neighborhood: "Emerald Bay",
  },
  {
    id: "demo-deal-4",
    property: "702 Elm Estate, Nashville TN",
    buyer: "Owen Mitchell",
    seller: "Cedar Crest Partners",
    closedOn: dateDaysAgo(45),
    price: "$1,740,000",
    commission: "$52,200",
    neighborhood: "Brentwood",
  },
  {
    id: "demo-deal-5",
    property: "510 Skyline Terrace, Denver CO",
    buyer: "Isabella Collins",
    seller: "Summit Ridge Holdings",
    closedOn: dateDaysAgo(51),
    price: "$1,180,000",
    commission: "$35,400",
    neighborhood: "Washington Park",
  },
  {
    id: "demo-deal-6",
    property: "550 Lakeshore Dr, Chicago IL",
    buyer: "Harper Lee",
    seller: "Lakefront Residences",
    closedOn: dateDaysAgo(63),
    price: "$1,640,000",
    commission: "$49,200",
    neighborhood: "Streeterville",
  },
  {
    id: "demo-deal-7",
    property: "212 Highline Court, Seattle WA",
    buyer: "Riley Matthews",
    seller: "Skybridge Homes",
    closedOn: dateDaysAgo(78),
    price: "$1,280,000",
    commission: "$38,400",
    neighborhood: "Queen Anne",
  },
  {
    id: "demo-deal-8",
    property: "97 Marbella Cove, Miami FL",
    buyer: "Sofia Torres",
    seller: "Oceanfront Estates",
    closedOn: dateDaysAgo(84),
    price: "$1,920,000",
    commission: "$57,600",
    neighborhood: "South of Fifth",
  },
  {
    id: "demo-deal-9",
    property: "441 Barton Springs Rd, Austin TX",
    buyer: "Michael Nguyen",
    seller: "Urban Edge Development",
    closedOn: dateDaysAgo(91),
    price: "$1,560,000",
    commission: "$46,800",
    neighborhood: "Barton Springs",
  },
  {
    id: "demo-deal-10",
    property: "33 Summit Blvd, San Francisco CA",
    buyer: "David Chen",
    seller: "Summit Estates LLC",
    closedOn: dateDaysAgo(108),
    price: "$2,780,000",
    commission: "$83,400",
    neighborhood: "Nob Hill",
  },
];

const conversationTemplates = [
  {
    summary: "Tour scheduling and brochure follow up",
    messages: [
      { sender: "client", body: "When can we visit the modern build on Ocean Drive?" },
      { sender: "agent", body: "Thursday at 4pm is open. Should I lock that in?" },
      { sender: "client", body: "That works. Please send the brochure beforehand." },
      { sender: "assistant", body: "Tour confirmed for Thursday 4pm. Brochure emailed with highlights." },
    ],
  },
  {
    summary: "Financing documents update",
    messages: [
      { sender: "client", body: "I uploaded the new pre-approval. Did it come through?" },
      { sender: "agent", body: "Yes, reviewed. We can strengthen offers with 30-day close now." },
      { sender: "client", body: "Great. Let's go aggressive on the Lakeview property." },
      { sender: "assistant", body: "Offer draft updated with 30-day close and escalation clause." },
    ],
  },
  {
    summary: "Inspection prep and contractor intros",
    messages: [
      { sender: "client", body: "Any tips before tomorrow's inspection?" },
      { sender: "agent", body: "Expect HVAC notes. I'll have my contractor ready for estimates." },
      { sender: "client", body: "Perfect. Send me their details so I can coordinate." },
      { sender: "assistant", body: "Shared contractor contact sheet and inspection day checklist." },
    ],
  },
  {
    summary: "Offer counter strategy",
    messages: [
      { sender: "client", body: "Seller countered with 785k and wants a 15-day option. Thoughts?" },
      { sender: "agent", body: "We can meet price but shorten option to 10 days with appraisal waiver." },
      { sender: "client", body: "I like that. Draft it and I'll sign tonight." },
      { sender: "assistant", body: "Counter drafted with updated terms and routed for e-signature." },
    ],
  },
  {
    summary: "Post-close concierge follow up",
    messages: [
      { sender: "client", body: "The move went smooth. Any recommendations for landscape design?" },
      { sender: "agent", body: "Absolutely. Sending over two luxury landscape teams I trust." },
      { sender: "client", body: "Amazing. Thanks for staying on top of everything." },
      { sender: "assistant", body: "Shared curated vendor list and scheduled follow-up for next week." },
    ],
  },
  {
    summary: "Showing feedback and next steps",
    messages: [
      { sender: "client", body: "How did the Sunday showings go?" },
      { sender: "agent", body: "Two buyers loved the staging. Expect an offer by Thursday." },
      { sender: "client", body: "Great. Let's line up a pricing strategy call tomorrow." },
      { sender: "assistant", body: "Strategy call set for 9am. Slide deck updated with comps." },
    ],
  },
  {
    summary: "Neighborhood insights and school rankings",
    messages: [
      { sender: "client", body: "Can you send school rankings for Rollingwood?" },
      { sender: "agent", body: "Highest rated is Rollingwood Academy. I'll send the full breakdown." },
      { sender: "client", body: "Perfect. Hudson really wants that dual language program." },
      { sender: "assistant", body: "Delivered school comparison report with commute times." },
    ],
  },
  {
    summary: "Luxury rental transition plan",
    messages: [
      { sender: "client", body: "Need a rental while my new build finishes. Any ideas?" },
      { sender: "agent", body: "I have a furnished penthouse available starting next week." },
      { sender: "client", body: "Lock it in for six months and send lease details." },
      { sender: "assistant", body: "Lease packet uploaded and DocuSign invitation sent." },
    ],
  },
];

const conversationClients = [
  { name: "Sarah Williams", property: "1180 Barton View", hue: 210 },
  { name: "David Chen", property: "33 Summit Boulevard", hue: 45 },
  { name: "Olivia Martinez", property: "19 Seaside Lane", hue: 165 },
  { name: "Marcus Johnson", property: "702 Rainier Court", hue: 12 },
  { name: "Priya Patel", property: "88 Beacon Street", hue: 320 },
  { name: "Ethan Brooks", property: "52 Modern Ridge", hue: 190 },
  { name: "Hannah Kim", property: "401 Skyline Avenue", hue: 270 },
  { name: "Jackson Rivera", property: "97 Marbella Cove", hue: 140 },
  { name: "Emily Thompson", property: "221 Peachtree Upper", hue: 28 },
  { name: "Noah Garcia", property: "414 Highland Estates", hue: 195 },
  { name: "Ava Robinson", property: "612 South End Row", hue: 260 },
  { name: "Liam Bennett", property: "18 Beacon Loft", hue: 30 },
  { name: "Isabella Collins", property: "510 Skyline Terrace", hue: 205 },
  { name: "Michael Nguyen", property: "441 Barton Springs", hue: 10 },
  { name: "Zoe Harris", property: "77 Harbor View", hue: 280 },
  { name: "Henry Clark", property: "33 Memorial Oaks", hue: 35 },
  { name: "Layla Anderson", property: "190 Alder Grove", hue: 155 },
  { name: "Mateo Sanchez", property: "522 Hill Country Rise", hue: 18 },
  { name: "Harper Lee", property: "750 Lakeshore Residences", hue: 220 },
  { name: "Sofia Torres", property: "97 Marbella Cove", hue: 150 },
  { name: "Mason Hughes", property: "18 Desert Bloom", hue: 15 },
  { name: "Grace Walker", property: "421 Ocean Crest", hue: 180 },
  { name: "Julian Perez", property: "88 Wythe Avenue", hue: 330 },
  { name: "Chloe Adams", property: "441 North River", hue: 205 },
  { name: "Nathan Scott", property: "511 Franklin Pike", hue: 40 },
  { name: "Maya Foster", property: "101 Seabreeze Point", hue: 170 },
  { name: "Lucas Ramirez", property: "81 River Oaks", hue: 25 },
  { name: "Gianna Russo", property: "212 Mercer Lofts", hue: 300 },
  { name: "Elijah Brooks", property: "200 Walnut Estates", hue: 55 },
  { name: "Aria Morgan", property: "707 Midtown Highline", hue: 260 },
  { name: "Carter Long", property: "912 Harbor North", hue: 200 },
  { name: "Penelope Ward", property: "155 Mountain Crest", hue: 125 },
  { name: "Dominic Price", property: "444 Sky Harbor", hue: 15 },
  { name: "Victoria Blake", property: "288 Beacon Court", hue: 24 },
  { name: "Sebastian Cruz", property: "99 Jackson Heights", hue: 340 },
  { name: "Nora Simmons", property: "622 Uptown Ridge", hue: 210 },
  { name: "Adrian Flores", property: "88 Apex Summit", hue: 12 },
  { name: "Riley Matthews", property: "510 Lakeside Manor", hue: 190 },
  { name: "Stella Cooper", property: "371 Magnifique", hue: 275 },
  { name: "Owen Mitchell", property: "702 Brentwood Reserve", hue: 30 },
];

export const demoConversationLibrary: DemoConversation[] = conversationClients.map((client, index) => {
  const template = conversationTemplates[index % conversationTemplates.length];
  return {
    id: `demo-conversation-${index + 1}`,
    clientName: client.name,
    avatarHue: client.hue,
    property: client.property,
    summary: template.summary,
    unread: index % 7 === 0,
    messages: template.messages.map((message, messageIndex) => ({
      id: `demo-message-${index + 1}-${messageIndex + 1}`,
      sender: message.sender as "client" | "agent" | "assistant",
      body: message.body.replace("Ocean Drive", client.property),
      timestamp: dateDaysAgo(Math.floor(index / 3) + (template.messages.length - messageIndex)),
    })),
  };
});

export const demoPropertyLibrary: DemoProperty[] = [
  {
    id: "demo-property-1",
    title: "Glasshouse Estate Overlooking Zilker Park",
    image: "https://images.unsplash.com/photo-1505693314120-0d443867891c?auto=format&fit=crop&w=1200&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1505692794403-55b9b9d2a3aa?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1464146072230-91cabc968266?auto=format&fit=crop&w=1200&q=80",
    ],
    address: "721 Willow Drive, Austin, TX",
    price: "$2,280,000",
    bedrooms: 4,
    bathrooms: 4.5,
    area: "3,950 sq ft",
    description:
      "An architect-curated residence with panoramic park views, automatic glass walls, and a resort-grade infinity pool wrapped in limestone.",
    highlights: [
      "Poliform kitchen with integrated Wolf and Miele suite",
      "Cantilevered primary suite with spa hydrotherapy bath",
      "Solar array with battery wall and smart shading system",
      "Landscaped terraces with al fresco kitchen and plunge pool",
    ],
    url: "https://www.zillow.com/homedetails/721-Willow-Dr-Austin-TX/123456789_zpid/",
  },
  {
    id: "demo-property-2",
    title: "Skyline Penthouse above Miami Beach Marina",
    image: "https://images.unsplash.com/photo-1512914890250-353c67bd2acc?auto=format&fit=crop&w=1200&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1512914890276-607fd77765c5?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1505691723518-36a5ac3be353?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1600585154518-990dced4db0d?auto=format&fit=crop&w=1200&q=80",
    ],
    address: "400 Alton Road, Penthouse 3201, Miami Beach, FL",
    price: "$4,480,000",
    bedrooms: 3,
    bathrooms: 3.5,
    area: "3,200 sq ft",
    description:
      "Sunrise to sunset vistas over Biscayne Bay with dual-level glass walls, sculptural staircase, and private sky lounge with saltwater spa.",
    highlights: [
      "Boffi chef kitchen with waterfall marble island",
      "Primary sanctuary with champagne bar and couture dressing gallery",
      "Integrated Crestron home automation and Lutron lighting",
      "VIP marina slip with concierge yacht services",
    ],
    url: "https://www.zillow.com/homedetails/400-Alton-Rd-Miami-Beach-FL/2106401972_zpid/",
  },
  {
    id: "demo-property-3",
    title: "Modern Farmhouse Retreat in Brentwood",
    image: "https://images.unsplash.com/photo-1617099391243-74e4d5d19f2d?auto=format&fit=crop&w=1200&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1505691938895-1758d7feb511?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1600607687920-4e2a87b5c08d?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1600585154340-0ef3c08cc65f?auto=format&fit=crop&w=1200&q=80",
    ],
    address: "702 Brentwood Reserve Lane, Nashville, TN",
    price: "$3,050,000",
    bedrooms: 5,
    bathrooms: 5.5,
    area: "5,240 sq ft",
    description:
      "Gated Brentwood escape with vaulted timber ceilings, bourbon library, and disappearing walls opening to a resort-size veranda.",
    highlights: [
      "Gourmet scullery with dual Sub-Zero towers and hidden pantry",
      "Club-level home theater and acoustic recording lounge",
      "Zero-edge pool with limestone deck and lanai fireplace",
      "Smart irrigation, Tesla wall chargers, and whole-home generator",
    ],
    url: "https://www.zillow.com/homedetails/702-Brentwood-Reserve-Ln-Brentwood-TN/234567890_zpid/",
  },
  {
    id: "demo-property-4",
    title: "Sunset Canyon Glass Villa",
    image: "https://images.unsplash.com/photo-1516455590571-18256e5bb9ff?auto=format&fit=crop&w=1200&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1502005097973-6a7082348e28?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1600585154487-00f6be23f5da?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1200&q=80",
    ],
    address: "522 Hill Country Rise, Austin, TX",
    price: "$2,780,000",
    bedrooms: 4,
    bathrooms: 4,
    area: "4,300 sq ft",
    description:
      "Floating over Barton Creek Preserve with polished concrete floors, organic stone accents, and panoramic canyon views.",
    highlights: [
      "Glass cube great room with floating hearth and designer lighting",
      "Catering caliber kitchen with Gaggenau suite and climate wine wall",
      "Primary wing with Japanese soaking tub and curated aromatherapy lounge",
      "Tiered outdoor living with sunken conversation pit and starlit spa",
    ],
    url: "https://www.zillow.com/homedetails/522-Hill-Country-Rise-Austin-TX/345678901_zpid/",
  },
  {
    id: "demo-property-5",
    title: "Chelsea Gallery Loft with Private Roof Garden",
    image: "https://images.unsplash.com/photo-1505693314120-0d443867891c?auto=format&fit=crop&w=1200&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1501183638710-841dd1904471?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1505691938895-1758d7feb511?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1505691723518-36a5ac3be353?auto=format&fit=crop&w=1200&q=80",
    ],
    address: "212 Mercer Lofts, Penthouse B, New York, NY",
    price: "$5,260,000",
    bedrooms: 3,
    bathrooms: 3,
    area: "2,980 sq ft",
    description:
      "Art collector's dream with 14-foot ceilings, industrial casement windows, and a curated roof garden designed for gallery events.",
    highlights: [
      "Custom Bulthaup kitchen framed in honed marble",
      "Primary suite with leather paneled dressing lounge and spa wet room",
      "Private roof terrace with outdoor cinema and catering kitchen",
      "Gated elevator access with double height foyer and sculpture niche",
    ],
    url: "https://www.zillow.com/homedetails/212-Mercer-St-New-York-NY/456789012_zpid/",
  },
  {
    id: "demo-property-6",
    title: "Laguna Tide Villa with Cliffside Infinity Pool",
    image: "https://images.unsplash.com/photo-1505691723518-36a5ac3be353?auto=format&fit=crop&w=1200&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1507089947368-19c1da9775ae?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1523217582562-09d0def993a6?auto=format&fit=crop&w=1200&q=80",
    ],
    address: "19 Seaside Lane, Laguna Beach, CA",
    price: "$6,450,000",
    bedrooms: 5,
    bathrooms: 6,
    area: "4,860 sq ft",
    description:
      "Cantilevered masterpiece with cascading water features, glass-floor corridor, and unparalleled Pacific panoramas from every suite.",
    highlights: [
      "Italian travertine chef kitchen with concealed prep gallery",
      "Wellness wing with salt therapy suite and oxygen lounge",
      "Tiered infinity pool with basalt fire bowls and coastal cabana",
      "Automated shades, fragrance system, and voice-activated concierge",
    ],
    url: "https://www.zillow.com/homedetails/19-Seaside-Ln-Laguna-Beach-CA/567890123_zpid/",
  },
];

export const demoNotifications: DemoNotification[] = [
  {
    id: "demo-notification-1",
    title: "New lead assigned",
    detail: "AI concierge routed Sarah Williams to your pipeline after scoring 91.",
    timestamp: dateDaysAgo(0),
  },
  {
    id: "demo-notification-2",
    title: "Document processed",
    detail: "Inspection report for 77 Harbor View is tagged and ready for review.",
    timestamp: dateDaysAgo(1),
  },
];

export const demoInsight =
  "Pipeline humming across Austin, Miami, and Boston. Top priorities: finalize Brentwood counter offer, send concierge review drip to Jackson Rivera, and stage Willow Drive for twilight showings. Marketing highlights ready for Thursday blitz campaign.";
